# 下記コマンドにより上位ディレクトリの.envのファイルを読み込む
# docker-compose --env-file ./.env -f docker/docker-compose.yml xxxx
version: '3'

name: clean-architecture-golang

services:
  app:
    container_name: clean-go-api
    build:
      context: ../
      dockerfile: docker/app/Dockerfile
    ports:
      - 8080:${SERVER_PORT}
    depends_on:
      - database_master
      - database_slave
    volumes:
      - ../app:/var/www/html
      # - ../nginx/config/default.conf:/etc/nginx/conf.d/default.conf
      - ../.bashrc:/root/.bashrc
    networks:
      - clean-architecture-golang-network

  database_master:
    container_name: clean_go_db_master
    build:
      context: ../
      dockerfile: docker/mysql/master/Dockerfile
    ports:
      - 3306:${DB_PORT}
    expose:
      - ${DB_PORT}
    restart: always
    # コンテナ外からの接続権限を与える
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASS}'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: '${DB_NAME}'
      # MYSQL_USER: '${DB_USER}'
      # MYSQL_PASSWORD: '${DB_PASS}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - ../mysql/master/data:/var/lib/mysql
      - ../mysql/master/sql:/sql
    # cap_add:
    #   - SYS_NICE #追加
    networks:
      - clean-architecture-golang-network

  database_slave:
    container_name: clean_go_db_slave
    build:
      context: ../
      dockerfile: docker/mysql/slave/Dockerfile
    ports:
      - 13306:${DB_PORT}
    expose:
      - ${DB_PORT}
    restart: always
    # コンテナ外からの接続権限を与える
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASS}'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: '${DB_NAME}'
      # MYSQL_USER: '${DB_USER}'
      # MYSQL_PASSWORD: '${DB_PASS}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - ../mysql/slave/data:/var/lib/mysql
      - ../mysql/slave/sql:/sql
    # cap_add:
    #   - SYS_NICE #追加
    networks:
      - clean-architecture-golang-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: database_master
      PMA_USER: root
      PMA_PASSWORD: password
    ports:
      - 18081:80
    depends_on:
      - database_master
    networks:
      - clean-architecture-golang-network

networks:
  clean-architecture-golang-network:
    name: clean_architecture_golang_network
